// GENERATED by build_portable.mjs - do not edit by hand. Standalone copy of the MarketRadar stateless API (chain RPC, THORChain, native-coin explorers, market data, Solana/Tron/TON).
const CORS_HEADERS = { "access-control-allow-origin": "*", "access-control-allow-methods": "GET", "content-type": "application/json" };
const CORS_HEADERS_POST = { "access-control-allow-origin": "*", "access-control-allow-methods": "GET, POST, OPTIONS", "access-control-allow-headers": "content-type", "content-type": "application/json" };
const SOLANA_FALLBACK_RPC = "https://solana-rpc.publicnode.com";
var SOLANA_RPC_ALLOWED = /* @__PURE__ */ new Set([
  "getAccountInfo",
  "getMultipleAccounts",
  "getProgramAccounts",
  "getBalance",
  "getLatestBlockhash",
  "isBlockhashValid",
  "getBlockHeight",
  "getSlot",
  "getEpochInfo",
  "getMinimumBalanceForRentExemption",
  "getFeeForMessage",
  "getRecentPrioritizationFees",
  "getSignatureStatuses",
  "getSignaturesForAddress",
  "getTransaction",
  "getParsedTransaction",
  "sendTransaction",
  "simulateTransaction",
  "getTokenAccountsByOwner",
  "getTokenAccountBalance",
  "getTokenSupply",
  "getTokenLargestAccounts",
  "getGenesisHash",
  "getVersion",
  "getHealth",
  "getSupply",
  "getBlock",
  "getBlocks",
  "getAddressLookupTable"
]);
// in-memory shims for what the Cloudflare runtime provides
const __store = new Map();
if (typeof globalThis.caches === "undefined" || !globalThis.caches.default) {
  globalThis.caches = { default: {
    async match(req) { const e = __store.get(req.url); if (!e) return undefined; if (e.exp < Date.now()) { __store.delete(req.url); return undefined; } return new Response(e.body, { headers: e.headers }); },
    async put(req, res) { const m = /max-age=(\d+)/.exec(res.headers.get("cache-control") || ""); if (__store.size > 800) __store.delete(__store.keys().next().value); __store.set(req.url, { body: await res.text(), headers: [...res.headers], exp: Date.now() + (m ? Number(m[1]) : 60) * 1000 }); }
  } };
}
const __hits = new Map();
async function mrwLimited(env, binding, key, ip) {
  const k = key + ":" + (ip || "anon"), now = Date.now(), cur = __hits.get(k);
  if (!cur || now - cur.t > 60000) { __hits.set(k, { t: now, n: 1 }); if (__hits.size > 5000) __hits.delete(__hits.keys().next().value); return false; }
  cur.n++; return cur.n > 90;
}
function mrwTooMany() { return new Response(JSON.stringify({ error: "too many requests, try again later" }), { status: 429, headers: CORS_HEADERS_POST }); }
export async function handle(request, env) {
  env = env || (typeof process !== "undefined" ? process.env : {});
  const url = new URL(request.url);
  if (request.method === "OPTIONS") return new Response(null, { headers: CORS_HEADERS_POST });
  if (url.pathname === "/health") return new Response(JSON.stringify({ ok: true, t: Date.now() }), { headers: CORS_HEADERS });
    if (url.pathname === "/evm-rpc" && request.method === "OPTIONS") return new Response(null, { headers: CORS_HEADERS_POST });
    if (url.pathname === "/evm-rpc" && request.method === "POST") {
      // JSON-RPC proxy for the in-app EVM buy flow (Ethereum / BNB Chain / Robinhood Chain). The Alchemy key stays here; only a whitelist of methods is forwarded.
      try {
        if (await mrwLimited(env, "RPC_LIMIT", "evmrpc", request.headers.get("x-mrw-client-ip") || request.headers.get("cf-connecting-ip"))) return mrwTooMany();
        const b = await request.json();
        const host = { eth: "eth-mainnet", bsc: "bnb-mainnet", robinhood: "robinhood-mainnet", base: "base-mainnet", arb: "arb-mainnet", polygon: "polygon-mainnet", op: "opt-mainnet" }[String(b.chain)];
        const ok = ["eth_call", "eth_getBalance", "eth_getTransactionCount", "eth_gasPrice", "eth_estimateGas", "eth_sendRawTransaction", "eth_getTransactionReceipt", "eth_chainId", "eth_blockNumber", "eth_getCode", "eth_getLogs", "eth_getBlockByNumber"];
        // eth_getLogs only for the Uniswap V4 PoolManagers (to read a pool key from its Initialize event); blocks for timestamps.
        const V4PM = ["0x000000000004444c5dc75cb358380d2e3de08a90", "0x28e2ea090877bf75740558f6bfb36a5ffee9e9df", "0x8366a39cc670b4001a1121b8f6a443a643e40951"];
        if (b.method === "eth_getLogs" && !(b.params[0] && V4PM.indexOf(String(b.params[0].address || "").toLowerCase()) >= 0 && Array.isArray(b.params[0].topics) && b.params[0].topics.length >= 2)) return new Response(JSON.stringify({ error: { message: "bad request" } }), { status: 400, headers: CORS_HEADERS_POST });
        const PUB = { eth: ["https://ethereum-rpc.publicnode.com", "https://eth.drpc.org", "https://rpc.mevblocker.io", "https://eth-mainnet.public.blastapi.io"], bsc: ["https://bsc-dataseed.binance.org", "https://bsc-rpc.publicnode.com", "https://bsc.drpc.org", "https://bsc-dataseed1.defibit.io"], base: ["https://mainnet.base.org", "https://base-rpc.publicnode.com", "https://base.drpc.org"], arb: ["https://arb1.arbitrum.io/rpc", "https://arbitrum-one-rpc.publicnode.com", "https://arbitrum.drpc.org"], polygon: ["https://polygon-bor-rpc.publicnode.com", "https://polygon.drpc.org", "https://polygon.api.onfinality.io/public"], op: ["https://mainnet.optimism.io", "https://optimism-rpc.publicnode.com", "https://optimism.drpc.org"] };
        const provs = (PUB[String(b.chain)] || []).slice();
        const rot = Math.floor(Math.random() * Math.max(1, provs.length)); const ordered = provs.slice(rot).concat(provs.slice(0, rot));
        if (host && env.ALCHEMY_API_KEY) ordered.push("https://" + host + ".g.alchemy.com/v2/" + String(env.ALCHEMY_API_KEY).trim());
        if (!ordered.length || ok.indexOf(String(b.method)) < 0 || !Array.isArray(b.params) || JSON.stringify(b.params).length > 20000) return new Response(JSON.stringify({ error: { message: "bad request" } }), { status: 400, headers: CORS_HEADERS_POST });
        // Several independent providers per chain, tried in turn: a provider that is down, rate-limited or does not answer in 6 s is skipped; a real contract revert is returned to the caller as is.
        const body = JSON.stringify({ jsonrpc: "2.0", id: 1, method: b.method, params: b.params });
        for (const u of ordered) {
          try {
            const r = await fetch(u, { method: "POST", headers: { "content-type": "application/json" }, body, signal: AbortSignal.timeout(6000) });
            if (!r.ok) continue;
            const txt = await r.text(); let j; try { j = JSON.parse(txt); } catch (e) { continue; }
            if (j && j.error && /rate|limit|capacity|overload|timeout|busy|unavailable|not enabled|api key|too many|exceed|forbidden|denied|disabled/i.test(String(j.error.message || ""))) continue;
            return new Response(txt, { headers: CORS_HEADERS_POST });
          } catch (e) {}
        }
        return new Response(JSON.stringify({ error: { message: "all providers failed" } }), { status: 502, headers: CORS_HEADERS_POST });
      } catch (e) {
        console.log("evm-rpc failed", e && e.message);
        return new Response(JSON.stringify({ error: { message: "rpc failed" } }), { status: 502, headers: CORS_HEADERS_POST });
      }
    }
    if (url.pathname === "/nc-api" && request.method === "POST") {
      // Native-coin helper (LTC / DOGE / BCH / XRP): balances, unspent outputs, fee rate and broadcast through several public explorers with fallback, so the browser never depends on one source. Read + broadcast only: no keys ever reach us.
      if (await mrwLimited(env, "API_LIMIT", "ncapi", request.headers.get("cf-connecting-ip"))) return mrwTooMany();
      const J = (o, st) => new Response(JSON.stringify(o), { status: st || 200, headers: CORS_HEADERS_POST });
      try {
        const b = await request.json();
        const chain = String(b.chain || ""), op = String(b.op || "");
        const addr = String(b.addr || "").slice(0, 120), hex = String(b.hex || "").slice(0, 400000);
        const okAddr = { btc: /^(bc1[a-z0-9]{20,90}|[13][1-9A-HJ-NP-Za-km-z]{24,34})$/, ltc: /^ltc1[a-z0-9]{20,80}$/, doge: /^D[1-9A-HJ-NP-Za-km-z]{24,34}$/, bch: /^(bitcoincash:)?[qp][a-z0-9]{40,45}$/, xrp: /^r[1-9A-HJ-NP-Za-km-z]{24,34}$/ };
        if (!okAddr[chain]) return J({ ok: false, error: "bad chain" }, 400);
        if (op !== "fee" && op !== "push" && op !== "submit" && !okAddr[chain].test(addr)) return J({ ok: false, error: "bad address" }, 400);
        const tj = async (u, init) => { const r = await fetch(u, init); if (!r.ok) throw new Error("http " + r.status); return r.json(); };
        const tt = async (u, init) => { const r = await fetch(u, init); const t = await r.text(); if (!r.ok) throw new Error(t.slice(0, 200)); return t; };
        const blockbook = { ltc: "https://litecoinblockexplorer.net", bch: "https://bchblockexplorer.com" };
        if (chain === "btc") {
          // Bitcoin through several independent Esplora-compatible explorers, tried in turn.
          const bases = ["https://blockstream.info/api", "https://mempool.space/api", "https://mempool.emzy.de/api"];
          const rot = Math.floor(Math.random() * bases.length), ord = bases.slice(rot).concat(bases.slice(0, rot));
          const tryAll = async (fn) => { let last = null; for (const bs of ord) { try { return await fn(bs); } catch (e) { last = e; } } throw last || new Error("no source"); };
          const T6 = () => ({ signal: AbortSignal.timeout(7000) });
          if (op === "fee") { const d = await tryAll(async (bs) => tj(bs + "/fee-estimates", T6())); return J({ ok: true, rate: Math.max(2, Math.ceil(d["6"] || d["12"] || 3)) }); }
          if (op === "bal") { const d = await tryAll(async (bs) => tj(bs + "/address/" + addr, T6())); return J({ ok: true, balance: (d.chain_stats.funded_txo_sum || 0) - (d.chain_stats.spent_txo_sum || 0) }); }
          if (op === "utxo") { const u = await tryAll(async (bs) => tj(bs + "/address/" + addr + "/utxo", T6())); return J({ ok: true, utxos: u.filter((x) => /^[0-9a-f]{64}$/.test(x.txid) && x.value > 0).map((x) => ({ txid: x.txid, vout: x.vout, value: x.value, conf: x.status && x.status.confirmed ? 1 : 0 })).slice(0, 200) }); }
          if (op === "push") { if (!/^[0-9a-fA-F]{100,400000}$/.test(hex)) return J({ ok: false, error: "bad tx" }, 400); const t = await tryAll(async (bs) => tt(bs + "/tx", { method: "POST", body: hex, signal: AbortSignal.timeout(9000) })); return /^[0-9a-f]{64}$/i.test(t.trim()) ? J({ ok: true, txid: t.trim() }) : J({ ok: false, error: "rejected" }, 502); }
          return J({ ok: false, error: "bad op" }, 400);
        }
        if (chain === "xrp") {
          const nodes = ["https://xrplcluster.com", "https://s1.ripple.com:51234", "https://s2.ripple.com:51234"];
          const rpc = async (method, params) => {
            let last = null;
            for (const n of nodes) { try { const j = await tj(n, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ method, params: [params] }) }); if (j && j.result && !/^(tooBusy|slowDown|noNetwork|noCurrent|noClosed)$/.test(String(j.result.error || ""))) return j.result; } catch (e) { last = e; } }
            throw last || new Error("no node");
          };
          if (op === "acct") {
            const r = await rpc("account_info", { account: addr, ledger_index: "current" });
            if (r.error === "actNotFound") return J({ ok: true, exists: false, balance: "0", sequence: 0 });
            if (!r.account_data) return J({ ok: false, error: r.error || "failed" }, 502);
            return J({ ok: true, exists: true, balance: String(r.account_data.Balance), sequence: r.account_data.Sequence, ownerCount: r.account_data.OwnerCount || 0, ledger: r.ledger_current_index || 0 });
          }
          if (op === "fee") {
            const r = await rpc("server_info", {});
            const v = (r.info && r.info.validated_ledger) || {};
            const f = await rpc("fee", {});
            return J({ ok: true, feeDrops: String((f.drops && f.drops.open_ledger_fee) || (f.drops && f.drops.base_fee) || "10"), reserveBase: String(Math.round((v.reserve_base_xrp || 1) * 1e6)), reserveInc: String(Math.round((v.reserve_inc_xrp || 0.2) * 1e6)), ledger: Number(f.ledger_current_index) || (v.seq || 0) });
          }
          if (op === "dest") {
            const r = await rpc("account_info", { account: addr, ledger_index: "validated" });
            if (r.error === "actNotFound") return J({ ok: true, exists: false, needTag: false });
            const fl = (r.account_data && r.account_data.Flags) || 0;
            return J({ ok: true, exists: true, needTag: !!(fl & 0x20000), blockIncoming: !!(fl & 0x00010000) });
          }
          if (op === "submit") {
            if (!/^[0-9A-Fa-f]{100,4000}$/.test(String(b.blob || ""))) return J({ ok: false, error: "bad blob" }, 400);
            const r = await rpc("submit", { tx_blob: String(b.blob) });
            return J({ ok: /^tes|^terQUEUED/.test(String(r.engine_result || "")), result: r.engine_result, message: r.engine_result_message, txid: r.tx_json && r.tx_json.hash });
          }
          return J({ ok: false, error: "bad op" }, 400);
        }
        if (op === "fee") {
          if (chain === "ltc") { try { const f = await tj("https://litecoinspace.org/api/v1/fees/recommended"); return J({ ok: true, rate: Math.max(2, Math.ceil(f.halfHourFee || 2)) }); } catch (e) { return J({ ok: true, rate: 5 }); } }
          if (chain === "doge") return J({ ok: true, rate: 150000 }); // sat per byte = 1.5 DOGE per kB
          return J({ ok: true, rate: 2 });
        }
        if (op === "utxo" || op === "bal") {
          let list = null;
          if (chain === "ltc") {
            try { const u = await tj("https://litecoinspace.org/api/address/" + addr + "/utxo"); list = u.map((x) => ({ txid: x.txid, vout: x.vout, value: x.value, conf: x.status && x.status.confirmed ? 1 : 0 })); } catch (e) {}
          }
          if (!list && blockbook[chain]) {
            try { const u = await tj(blockbook[chain] + "/api/v2/utxo/" + addr); list = u.map((x) => ({ txid: x.txid, vout: x.vout, value: Number(x.value), conf: x.confirmations > 0 ? 1 : 0 })); } catch (e) {}
          }
          if (!list && chain === "ltc") {
            try { const u = await tj("https://api.blockcypher.com/v1/ltc/main/addrs/" + addr + "?unspentOnly=true&limit=200"); list = (u.txrefs || []).map((x) => ({ txid: x.tx_hash, vout: x.tx_output_n, value: x.value, conf: x.confirmations > 0 ? 1 : 0 })); } catch (e) {}
          }
          if (!list && chain === "doge") {
            try { const u = await tj("https://api.blockcypher.com/v1/doge/main/addrs/" + addr + "?unspentOnly=true&limit=200"); list = (u.txrefs || []).map((x) => ({ txid: x.tx_hash, vout: x.tx_output_n, value: x.value, conf: x.confirmations > 0 ? 1 : 0 })); } catch (e) {}
            if (!list) { try { const u = await tj("https://api.blockchair.com/dogecoin/dashboards/address/" + addr + "?limit=0,200"); const d = u.data && u.data[addr]; list = ((d && d.utxo) || []).map((x) => ({ txid: x.transaction_hash, vout: x.index, value: x.value, conf: x.block_id > 0 ? 1 : 0 })); } catch (e) {} }
          }
          if (!list && chain === "bch") {
            try { const u = await tj("https://api.blockchair.com/bitcoin-cash/dashboards/address/" + addr.replace("bitcoincash:", "") + "?limit=0,200"); const d = u.data && Object.values(u.data)[0]; list = ((d && d.utxo) || []).map((x) => ({ txid: x.transaction_hash, vout: x.index, value: x.value, conf: x.block_id > 0 ? 1 : 0 })); } catch (e) {}
          }
          if (!list) return J({ ok: false, error: "sources unavailable" }, 502);
          if (op === "bal") return J({ ok: true, balance: list.reduce((a, x) => a + (x.value || 0), 0) });
          return J({ ok: true, utxos: list.filter((x) => /^[0-9a-f]{64}$/.test(x.txid) && x.value > 0).slice(0, 200) });
        }
        if (op === "push") {
          if (!/^[0-9a-fA-F]{100,400000}$/.test(hex)) return J({ ok: false, error: "bad tx" }, 400);
          let txid = null, err = "";
          const attempts = [];
          if (chain === "ltc") attempts.push(async () => (await tt("https://litecoinspace.org/api/tx", { method: "POST", body: hex })).trim());
          if (blockbook[chain]) attempts.push(async () => { const j = await tj(blockbook[chain] + "/api/v2/sendtx/" + hex); return j.result; });
          if (chain === "doge" || chain === "ltc") attempts.push(async () => { const j = await tj("https://api.blockcypher.com/v1/" + chain + "/main/txs/push", { method: "POST", body: JSON.stringify({ tx: hex }) }); return j.tx && j.tx.hash; });
          if (chain === "doge" || chain === "bch") attempts.push(async () => { const j = await tj("https://api.blockchair.com/" + (chain === "doge" ? "dogecoin" : "bitcoin-cash") + "/push/transaction", { method: "POST", headers: { "content-type": "application/x-www-form-urlencoded" }, body: "data=" + hex }); return j.data && j.data.transaction_hash; });
          for (const a of attempts) { try { const r = await a(); if (r && /^[0-9a-f]{64}$/i.test(r)) { txid = r; break; } } catch (e) { err = String(e.message || e).slice(0, 160); } }
          return txid ? J({ ok: true, txid }) : J({ ok: false, error: err || "rejected" }, 502);
        }
        return J({ ok: false, error: "bad op" }, 400);
      } catch (e) { return J({ ok: false, error: "failed" }, 500); }
    }
    if (url.pathname === "/thor-inbound" || url.pathname === "/thor-quote") {
      // THORChain through several independent public gateways. /thor-inbound asks ALL of them in parallel and only returns a vault/router row that AT LEAST TWO sources agree on (the safety check before any money moves). /thor-quote asks them in rotation and returns the first real answer.
      if (await mrwLimited(env, "API_LIMIT", "thorin", request.headers.get("cf-connecting-ip"))) return mrwTooMany();
      const SRC = ["https://gateway.liquify.com/chain/thorchain_api", "https://rest.cosmos.directory/thorchain", "https://thornode.ninerealms.com", "https://rpc.thorchain.network", "https://thornode.thorchain.liquify.com"];
      const fj = async (u) => { const r = await fetch(u, { headers: { accept: "application/json" }, signal: AbortSignal.timeout(7000) }); const t = await r.text(); let j = null; try { j = JSON.parse(t); } catch (e) {} return { ok: r.ok, j, t }; };
      if (url.pathname === "/thor-inbound") {
        const got = await Promise.all(SRC.map(async (b) => { try { const r = await fj(b + "/thorchain/inbound_addresses"); return r.ok && Array.isArray(r.j) ? { b, rows: r.j } : null; } catch (e) { return null; } }));
        const ok = got.filter(Boolean);
        if (ok.length < 2) return new Response(JSON.stringify({ error: "need two sources", sources: ok.length }), { status: 502, headers: CORS_HEADERS });
        const out = [];
        for (const row of ok[0].rows) {
          const key = (x) => String(x.address).toLowerCase() + "|" + String(x.router || "").toLowerCase() + "|" + (x.halted ? 1 : 0) + (x.global_trading_paused ? 1 : 0) + (x.chain_trading_paused ? 1 : 0);
          let agree = 0;
          for (const s of ok) { const m = s.rows.filter((x) => x.chain === row.chain)[0]; if (m && key(m) === key(row)) agree++; }
          if (agree >= 2) out.push(Object.assign({}, row, { agree }));
        }
        return new Response(JSON.stringify(out), { headers: { ...CORS_HEADERS, "x-thor-sources": String(ok.length) } });
      }
      const q = new URLSearchParams();
      for (const k of ["from_asset", "to_asset", "amount", "destination", "tolerance_bps", "streaming_interval", "streaming_quantity"]) { const v = url.searchParams.get(k); if (v) q.set(k, String(v).slice(0, 200)); }
      const rot = Math.floor(Math.random() * SRC.length), ord = SRC.slice(rot).concat(SRC.slice(0, rot));
      let firstErr = null;
      for (const base of ord) {
        try {
          const r = await fj(base + "/thorchain/quote/swap?" + q.toString());
          if (r.ok && r.j && r.j.inbound_address) return new Response(r.t, { headers: { ...CORS_HEADERS, "cache-control": "no-store", "x-thor-source": base.replace("https://", "").split("/")[0] } });
          if (r.j && r.j.message && !firstErr) firstErr = r.t;
        } catch (e) {}
      }
      return new Response(firstErr || JSON.stringify({ error: "unavailable" }), { status: firstErr ? 400 : 502, headers: CORS_HEADERS });
    }
    if (url.pathname === "/cg") {
      // CoinGecko through OUR edge cache so thousands of visitors share one upstream call: fresh copy 5 min (coin pages 6 h), and if CoinGecko is down or rate-limiting we keep serving the last good copy (up to 7 days) instead of an empty page.
      if (await mrwLimited(env, "API_LIMIT", "cgp", request.headers.get("cf-connecting-ip"))) return mrwTooMany();
      const kind = url.searchParams.get("p"), id = String(url.searchParams.get("id") || "").replace(/[^a-z0-9_-]/g, "").slice(0, 80);
      let up, ttl, upStatus = 0;
      if (kind === "markets") { up = "https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=200&page=1&sparkline=true&price_change_percentage=24h"; ttl = 300; }
      else if (kind === "coin" && id) { up = "https://api.coingecko.com/api/v3/coins/" + id + "?localization=false&tickers=false&market_data=false&community_data=false&developer_data=false&sparkline=false"; ttl = 21600; }
      else return new Response(JSON.stringify({ error: "bad request" }), { status: 400, headers: CORS_HEADERS });
      const cache = caches.default, freshKey = new Request("https://cg.mrw.internal/fresh/" + kind + "/" + id), staleKey = new Request("https://cg.mrw.internal/stale/" + kind + "/" + id);
      const hit = await cache.match(freshKey);
      if (hit) return new Response(hit.body, { headers: { ...CORS_HEADERS, "x-mrw-cache": "fresh" } });
      try {
        const r = await fetch(up, { headers: { accept: "application/json", "user-agent": "Mozilla/5.0 (compatible; MarketRadar/1.0; +https://marketradarwhale.com)" }, signal: AbortSignal.timeout(8000) });
        upStatus = r.status;
        if (r.ok) {
          const txt = await r.text();
          if (txt.length > 50) {
            await cache.put(freshKey, new Response(txt, { headers: { "cache-control": "public, max-age=" + ttl } }));
            await cache.put(staleKey, new Response(txt, { headers: { "cache-control": "public, max-age=604800" } }));
            return new Response(txt, { headers: { ...CORS_HEADERS, "x-mrw-cache": "miss" } });
          }
        }
      } catch (e) {}
      // second source: the snapshot our own GitHub Action publishes every 30 min (CoinGecko rate-limits shared Worker addresses, GitHub runners are not limited)
      try {
        const SNAP = "https://raw.githubusercontent.com/alihosseiniytm-stack/mr-channel-post/main/data/";
        if (kind === "markets") { const r = await fetch(SNAP + "markets.json", { signal: AbortSignal.timeout(8000), cf: { cacheTtl: 300, cacheEverything: true } }); if (r.ok) { const txt = await r.text(); if (txt.length > 1000) return new Response(txt, { headers: { ...CORS_HEADERS, "x-mrw-cache": "snapshot" } }); } }
        else { const r = await fetch(SNAP + "platforms.json", { signal: AbortSignal.timeout(8000), cf: { cacheTtl: 1800, cacheEverything: true } }); if (r.ok) { const pj = await r.json(); if (pj && pj[id]) return new Response(JSON.stringify({ id, platforms: pj[id] }), { headers: { ...CORS_HEADERS, "x-mrw-cache": "snapshot" } }); } }
      } catch (e) {}
      const st = await cache.match(staleKey);
      if (st) return new Response(st.body, { headers: { ...CORS_HEADERS, "x-mrw-cache": "stale" } });
      return new Response(JSON.stringify({ error: "unavailable", upstream: upStatus }), { status: 502, headers: CORS_HEADERS });
    }
    if (url.pathname === "/gt") {
      // GeckoTerminal through our edge cache: one upstream call serves every visitor, and the last good copy (up to 3 days) is served if it rate-limits or is down.
      if (await mrwLimited(env, "API_LIMIT", "gtp", request.headers.get("cf-connecting-ip"))) return mrwTooMany();
      const path = String(url.searchParams.get("p") || "");
      if (!/^(networks\/[a-z0-9_-]+\/(trending_pools|tokens\/[A-Za-z0-9]+(\/info|\/pools)?|pools\/[A-Za-z0-9]+(\/ohlcv\/[a-z]+)?)|search\/pools)(\?[A-Za-z0-9_=&%.,-]*)?$/.test(path) || path.length > 300) return new Response(JSON.stringify({ error: "bad request" }), { status: 400, headers: CORS_HEADERS });
      const cache = caches.default, fk = new Request("https://gt.mrw.internal/f/" + encodeURIComponent(path)), sk = new Request("https://gt.mrw.internal/s/" + encodeURIComponent(path));
      const hit = await cache.match(fk);
      if (hit) return new Response(hit.body, { headers: { ...CORS_HEADERS, "x-mrw-cache": "fresh" } });
      try {
        const r = await fetch("https://api.geckoterminal.com/api/v2/" + path, { headers: { accept: "application/json;version=20230302" }, signal: AbortSignal.timeout(8000) });
        if (r.ok) {
          const txt = await r.text();
          await cache.put(fk, new Response(txt, { headers: { "cache-control": "public, max-age=" + (path.indexOf("ohlcv") >= 0 ? 30 : 90) } }));
          await cache.put(sk, new Response(txt, { headers: { "cache-control": "public, max-age=259200" } }));
          return new Response(txt, { headers: { ...CORS_HEADERS, "x-mrw-cache": "miss" } });
        }
      } catch (e) {}
      const st = await cache.match(sk);
      if (st) return new Response(st.body, { headers: { ...CORS_HEADERS, "x-mrw-cache": "stale" } });
      return new Response(JSON.stringify({ error: "unavailable" }), { status: 502, headers: CORS_HEADERS });
    }
    if (url.pathname.startsWith("/tron/") || url.pathname.startsWith("/ton/")) {
      // Tron (TronGrid-compatible) and TON (toncenter v2-compatible) through several independent public providers in turn. Read + broadcast only; no keys here.
      if (request.method === "OPTIONS") return new Response(null, { headers: CORS_HEADERS_POST });
      if (await mrwLimited(env, "RPC_LIMIT", "tt", request.headers.get("x-mrw-client-ip") || request.headers.get("cf-connecting-ip"))) return mrwTooMany();
      const isTron = url.pathname.startsWith("/tron/");
      const sub = url.pathname.slice(isTron ? 5 : 4);
      const okPath = isTron ? /^\/(wallet|walletsolidity)\/[a-z]+$|^\/v1\/accounts\/[A-Za-z0-9]+(\/[a-z]+)?$|^\/jsonrpc$/ : /^\/(getAddressBalance|getAddressInformation|getWalletInformation|runGetMethod|sendBoc|sendBocReturnHash|jsonRPC|estimateFee|getTransactions|getMasterchainInfo|detectAddress)$/;
      if (!okPath.test(sub) || (request.method !== "GET" && request.method !== "POST")) return new Response(JSON.stringify({ error: "bad request" }), { status: 400, headers: CORS_HEADERS_POST });
      const bodyTxt = request.method === "POST" ? await request.text() : undefined;
      if (bodyTxt && bodyTxt.length > 200000) return new Response(JSON.stringify({ error: "too large" }), { status: 400, headers: CORS_HEADERS_POST });
      let bases;
      if (isTron) bases = ["https://api.trongrid.io", "https://api.tronstack.io", "https://tron.publicnode.com", "https://tron-mainnet.gateway.tatum.io"];
      else {
        bases = ["https://toncenter.com/api/v2"];
        try {
          const nodes = await (await fetch("https://ton.access.orbs.network/mngr/nodes?npm_version=2.3.3", { signal: AbortSignal.timeout(4000), cf: { cacheTtl: 600, cacheEverything: true } })).json();
          const healthy = nodes.filter((n) => n.Healthy === "1" && n.Mngr && n.Mngr.health && n.Mngr.health["v2-mainnet"]).map((n) => "https://ton.access.orbs.network/" + n.NodeId + "/1/mainnet/toncenter-api-v2");
          for (let i = healthy.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); const t = healthy[i]; healthy[i] = healthy[j]; healthy[j] = t; }
          bases = bases.concat(healthy.slice(0, 5));
        } catch (e) {}
      }
      const rot = Math.floor(Math.random() * bases.length), ord = bases.slice(rot).concat(bases.slice(0, rot));
      for (const b of ord) {
        try {
          const r = await fetch(b + sub + url.search, { method: request.method, headers: bodyTxt !== undefined ? { "content-type": "application/json" } : {}, body: bodyTxt, signal: AbortSignal.timeout(8000) });
          if (r.status === 429 || r.status >= 500 || r.status === 403 || r.status === 401) continue;
          const txt = await r.text();
          try { JSON.parse(txt); } catch (e) { continue; }
          return new Response(txt, { status: r.status, headers: CORS_HEADERS_POST });
        } catch (e) {}
      }
      return new Response(JSON.stringify({ error: "all providers failed" }), { status: 502, headers: CORS_HEADERS_POST });
    }
    if (url.pathname === "/solana-rpc" && request.method === "OPTIONS") {
      return new Response(null, { headers: CORS_HEADERS_POST });
    }
    if (url.pathname === "/solana-rpc" && request.method === "POST") {
      if (env.RPC_LIMIT) {
        const ip = request.headers.get("cf-connecting-ip") || "anon";
        try {
          const { success } = await env.RPC_LIMIT.limit({ key: "rpc:" + ip });
          if (!success) {
            return new Response(JSON.stringify({ error: "rate limited" }), {
              status: 429,
              headers: { ...CORS_HEADERS_POST, "retry-after": "60" }
            });
          }
        } catch {
        }
      }
      const upstream = env.HELIUS_RPC_URL || SOLANA_FALLBACK_RPC;
      let body;
      try {
        body = await request.json();
      } catch {
        return new Response(JSON.stringify({ error: "invalid JSON" }), { status: 400, headers: CORS_HEADERS_POST });
      }
      const calls = Array.isArray(body) ? body : [body];
      if (calls.length > 25) {
        return new Response(JSON.stringify({ error: "batch too large" }), { status: 400, headers: CORS_HEADERS_POST });
      }
      for (const c of calls) {
        if (!c || typeof c.method !== "string" || !SOLANA_RPC_ALLOWED.has(c.method)) {
          return new Response(JSON.stringify({ error: "method not allowed: " + (c && c.method || "?") }), { status: 403, headers: CORS_HEADERS_POST });
        }
      }
      // Several providers in turn (our Helius key first, then optional extra keys, then free public nodes): a provider that is down, rate-limited or silent for 8 s is skipped.
      const upstreams = [upstream, env.SOL_RPC_2, env.SOL_RPC_3, env.SOL_RPC_4, "https://solana-rpc.publicnode.com", "https://api.mainnet-beta.solana.com"].filter((u, i, a) => u && a.indexOf(u) === i);
      const sbody = JSON.stringify(body);
      for (const u of upstreams) {
        try {
          const r = await fetch(u, { method: "POST", headers: { "content-type": "application/json" }, body: sbody, signal: AbortSignal.timeout(8000) });
          if (!r.ok && r.status !== 400) continue;
          const txt = await r.text();
          if (/"code":\s*-32(429|005|029)|rate limit|too many requests|api key|unauthorized/i.test(txt.slice(0, 400)) && txt.length < 800) continue;
          return new Response(txt, { status: r.status, headers: CORS_HEADERS_POST });
        } catch (e) {}
      }
      return new Response(JSON.stringify({ error: "rpc upstream failed" }), { status: 502, headers: CORS_HEADERS_POST });
    }

  return new Response(JSON.stringify({ error: "not found" }), { status: 404, headers: CORS_HEADERS });
}
export default { fetch: handle };
